language: node_js
node_js:
    - "0.10"
after_script:
  - npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04a1d309aecd57e85996
    on_success: change
    on_failure: always
    on_start: false